src/main/java/com/danum/danum/exception/CustomJwtException.java, src/main/java/com/danum/danum/filter/JwtFilter.java
=> refactor: jwt 인증 필터 로직 수정

src/main/java/com/danum/danum/config/SecurityConfig.java
모든 경로 인증 예외 -> 로그인/회원가입/테스트만 인증 예외
=> config: 경로별 인증 설정 수정

src/main/java/com/danum/danum/service/member/MemberServiceImpl.java
=> refactor: refresh 토큰 쿠키 등록 시 이름 변경

src/main/java/com/danum/danum/controller/board/BoardController.java, src/main/java/com/danum/danum/controller/board/CommentController.java, src/main/java/com/danum/danum/service/board/BoardService.java
- Board Controller 폴더 구조 변경 (board 패키지)
- Comment Controller 폴더 구조 변경 (board 패키지)
- BoardService 인터페이스 내 @Service 어노테이션 제거
- BoardService 인터페이스 내 접근 제어자 제거
=> board 관련 내용 수정

src/main/java/com/danum/danum/controller/GlobalExceptionHandler.java, src/main/java/com/danum/danum/exception/BoardException.java, src/main/java/com/danum/danum/exception/CommentException.java, src/main/java/com/danum/danum/exception/CustomException.java, src/main/java/com/danum/danum/exception/CustomJwtException.java, src/main/java/com/danum/danum/exception/DiscordException.java, src/main/java/com/danum/danum/exception/ErrorResponse.java, src/main/java/com/danum/danum/exception/MemberException.java, src/main/java/com/danum/danum/service/member/MemberServiceImpl.java
- 사용자 지정 예외 일괄 처리를 위한 Custom Exception 추가
- 예외 응답을 위한 핸들러 추가
- 비밀번호 오류 시 발생하는 예외 변경
=> 전반적인 예외 처리 로직 수정

src/main/java/com/danum/danum/domain/member/Member.java
- ai result 객체 getter어노테이션 추가
- member 객체 getter메소드 삭제 후 getter 어노테이션 추가
=> getter문 추가

src/main/java/com/danum/danum/controller/ai/OpenAiController.java, src/main/java/com/danum/danum/domain/openai/OpenAiRequest.java, src/main/java/com/danum/danum/domain/openai/OpenAiResult.java
- request 전달 객체 추가
- request 처리 메소드 수정 (GET -> POST)
=> feat: open ai 로직 수정

src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/controller/board/VillageController.java
=> fix: url mapping 변경

src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/controller/board/VillageController.java, src/main/java/com/danum/danum/domain/board/question/Question.java, src/main/java/com/danum/danum/domain/board/question/QuestionMapper.java, src/main/java/com/danum/danum/domain/board/question/QuestionViewDto.java, src/main/java/com/danum/danum/domain/board/village/Village.java, src/main/java/com/danum/danum/domain/board/village/VillageMapper.java, src/main/java/com/danum/danum/domain/board/village/VillageViewDto.java, src/main/java/com/danum/danum/domain/member/Member.java, src/main/java/com/danum/danum/service/board/question/QuestionService.java, src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java, src/main/java/com/danum/danum/service/board/village/VillageService.java, src/main/java/com/danum/danum/service/board/village/VillageServiceImpl.java, src/test/java/com/danum/danum/QuestionTest.java, src/test/java/com/danum/danum/VillageTest.java
1. 게시판 로직 수정
2. Member Entity에 Email을 가져올 수 있도록 Getter 추가
=> [0608] 코드 업데이트 사항

src/main/java/com/danum/danum/controller/board/QuestionCommentController.java, src/main/java/com/danum/danum/controller/board/VillageCommentController.java, src/main/java/com/danum/danum/domain/comment/question/QuestionComment.java, src/main/java/com/danum/danum/domain/comment/question/QuestionCommentViewDto.java, src/main/java/com/danum/danum/domain/comment/village/VillageComment.java, src/main/java/com/danum/danum/domain/comment/village/VillageCommentViewDto.java, src/main/java/com/danum/danum/service/comment/QuestionCommentService.java, src/main/java/com/danum/danum/service/comment/QuestionCommentServiceImpl.java, src/main/java/com/danum/danum/service/comment/VillageCommentService.java, src/main/java/com/danum/danum/service/comment/VillageCommentServiceImpl.java
1. 댓글 기능이 잘 동작되게 수정
2. 댓글 기능 테스트 통과
=> feat: 댓글 로직 수정

src/main/java/com/danum/danum/handler/ChatPreHandler.java, src/main/java/com/danum/danum/service/chat/RedisSubscriber.java
ChatPreHandler - 인증로직 추가
RedisSubscriber - RedisSubscriber -> StringRedisSubscriber
=> fix : ChatPreHandler, RedisSubscriber logic fix

src/main/java/com/danum/danum/controller/board/QuestionCommentController.java, src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/controller/board/VillageCommentController.java, src/main/java/com/danum/danum/controller/board/VillageController.java, src/main/java/com/danum/danum/service/board/question/QuestionService.java, src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java, src/main/java/com/danum/danum/service/board/village/VillageService.java, src/main/java/com/danum/danum/service/board/village/VillageServiceImpl.java, src/main/java/com/danum/danum/service/comment/QuestionCommentService.java, src/main/java/com/danum/danum/service/comment/QuestionCommentServiceImpl.java, src/main/java/com/danum/danum/service/comment/VillageCommentService.java, src/main/java/com/danum/danum/service/comment/VillageCommentServiceImpl.java, src/test/java/com/danum/danum/QuestionCommentTest.java, src/test/java/com/danum/danum/QuestionTest.java, src/test/java/com/danum/danum/VillageCommentTest.java, src/test/java/com/danum/danum/VillageTest.java
1. 컨트롤러 게시판 및 댓글에 메소드명 수정
2. 서비스에서 생성할 때 created -> create 로 변경
=> [REFACTOR] Change Meshods name

src/main/java/com/danum/danum/controller/chat/ChatController.java, src/main/java/com/danum/danum/domain/chat/ChatMessage.java, src/main/java/com/danum/danum/repository/ChatRoomRepository.java, src/main/java/com/danum/danum/service/chat/ChatService.java
ChatController - 최근 대화 내역을 반환하는 api
ChatMessage - timestamp 메시지 전송 시간
ChatService - 사용자의 최근 대화 내역을 조회기능
ChatRoomRepository - Redis 저장소에 저장된 메시지만 표시
=> feat : Redis 저장소에 저장된 채팅내역 표시 기능

src/main/java/com/danum/danum/controller/chat/ChatController.java
ChatController
- @Controller -> @RestController 변경
- 최근 대화내역 반환 로직 GetMapping 주소 변경
=> rename: ChatController anotation, GetMapping

src/main/java/com/danum/danum/domain/member/MemberMapper.java, src/main/java/com/danum/danum/domain/member/RegisterDto.java
MemberMapper, RegisterDto 
latitude, longitude 추가
=> feat: latitude, longitude

src/main/java/com/danum/danum/domain/member/Member.java
=> style: Member

src/main/java/com/danum/danum/config/security/SecurityConfig.java
SecurityConfig -> SecurityFilterChain Cors설정
=> refactor: Security Cors

src/main/java/com/danum/danum/controller/admin/AdminController.java, src/main/java/com/danum/danum/domain/member/Member.java, src/main/java/com/danum/danum/repository/board/QuestionRepository.java, src/main/java/com/danum/danum/repository/board/VillageRepository.java, src/main/java/com/danum/danum/repository/comment/QuestionCommentRepository.java, src/main/java/com/danum/danum/repository/comment/VillageCommentRepository.java, src/main/java/com/danum/danum/service/admin/AdminService.java, src/main/java/com/danum/danum/service/admin/AdminServiceImpl.java
Member - setContribution 로직추가 ( 회원 상태 변화 )
AdminController - 어드민 전용 컨트롤러 로직 추가
VillageRepository - findAllByMember 추가
VillageCommentRepository - findAllByVillageId, findAllByMember 추가
QuestionRepository - findAllByMember추가
QuestionCommentRepository - findAllByQuestionId, findAllByMember
=> feat: Admin Controller Logic

src/main/java/com/danum/danum/domain/member/Member.java
Member - contribution 필드의 타입을 int에서 Integer로 변경
=> refactor: Member contribution

src/main/java/com/danum/danum/handler/ChatPreHandler.java
WebSocket - ws-stomp 연결 핸드쉐이크 과정 예외 및 유저초기화 로직
=> feat : ChatPreHandler

src/main/java/com/danum/danum/controller/chat/ChatController.java, src/main/java/com/danum/danum/controller/chat/ChatRoomController.java
=> refactor: Controller anotation

src/main/java/com/danum/danum/controller/admin/AdminController.java
AdminController - 질문 상세 조회 api 로직 추가
=> feat: AdminController logic

src/main/java/com/danum/danum/controller/chat/ChatController.java, src/main/java/com/danum/danum/controller/chat/ChatRoomController.java, src/main/java/com/danum/danum/domain/chat/ChatMessage.java, src/main/java/com/danum/danum/domain/chat/ChatRoom.java, src/main/java/com/danum/danum/repository/ChatRoomRepository.java
ChatController - 사용자 새 메시지 저장 및 발행 로직 추가 
ChatRoomController - 전반적인 로직 수정 및 1:1 매칭 채팅 api 구현
ChatRoomRepository  - 메시지 저장 및 발행, 1:1채팅방 CRUD 로직 구현
=> Feat : 1:1 채팅 로직

src/main/java/com/danum/danum/config/RedisConfig.java
RedisConfig 인증 절차중 Password 절차 주석해제
=> comment: RedisConfig Delete Annotation

src/main/java/com/danum/danum/controller/comment/QuestionCommentController.java, src/main/java/com/danum/danum/controller/comment/VillageCommentController.java, src/main/java/com/danum/danum/domain/comment/question/QuestionComment.java, src/main/java/com/danum/danum/domain/comment/village/VillageComment.java, src/main/java/com/danum/danum/domain/member/Member.java, src/main/java/com/danum/danum/exception/ErrorCode.java, src/main/java/com/danum/danum/repository/comment/QuestionCommentRepository.java, src/main/java/com/danum/danum/repository/comment/VillageCommentRepository.java, src/main/java/com/danum/danum/service/comment/QuestionCommentService.java, src/main/java/com/danum/danum/service/comment/QuestionCommentServiceImpl.java, src/main/java/com/danum/danum/service/comment/VillageCommentService.java, src/main/java/com/danum/danum/service/comment/VillageCommentServiceImpl.java, src/main/java/com/danum/danum/service/member/MemberService.java, src/main/java/com/danum/danum/service/member/MemberServiceImpl.java
Member - exp 경험치 시스템 추가 (기본 0 최대 100 )
question, villageComment Entity에 답변이 채택된 글인지 확인하는 Boolean형 필드 추가
question, villageCommentRepository - 답변과 채택된 글인지 확인하는 메소드추가
question, villageCommentService - 채택과 채택취소에대한 로직 구현
question, villageCommentController - 답변 채택, 채택 취소 API 구현
ErrorCode - 답변 채택에대한 커스텀 예외처리 작성
=> feat: Implement answer acceptance and user experience points

src/main/java/com/danum/danum/controller/MemberController.java, src/main/java/com/danum/danum/exception/ErrorCode.java, src/main/java/com/danum/danum/service/member/MemberService.java, src/main/java/com/danum/danum/service/member/MemberServiceImpl.java
Member, 서비스로직
contribution필드를 통한 회원 활성/정지 상태 로직 및 활성/정지 API구현
=> feat: Enable/Disable User Accounts

src/main/java/com/danum/danum/controller/GlobalExceptionHandler.java, src/main/java/com/danum/danum/controller/MemberController.java, src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/controller/board/VillageController.java, src/main/java/com/danum/danum/controller/jwt/AuthController.java, src/main/java/com/danum/danum/domain/board/question/Question.java, src/main/java/com/danum/danum/domain/board/question/QuestionUpdateDto.java, src/main/java/com/danum/danum/domain/board/village/Village.java, src/main/java/com/danum/danum/domain/board/village/VillageUpdateDto.java, src/main/java/com/danum/danum/exception/ErrorCode.java, src/main/java/com/danum/danum/service/board/question/QuestionService.java, src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java, src/main/java/com/danum/danum/service/board/village/VillageService.java, src/main/java/com/danum/danum/service/board/village/VillageServiceImpl.java, src/main/java/com/danum/danum/service/member/MemberService.java, src/main/java/com/danum/danum/service/member/MemberServiceImpl.java, src/main/java/com/danum/danum/util/jwt/JwtUtil.java
JwtUtil, AuthController
- JWT AccessToken 만료 검증 로직 및 API구현 
GlobalExceptionHandler
- AccessToken만료시 핸들러로 통한 커스텀예외 추가
Question, Village 게시판
- Update로직 및 API구현 
MemberController
- ADMIN권한으로 작동하는 사용자의 Email 가져오기 로직 및 API 구현
=> JWT AccessToken 만료 검증로직 구현

src/main/java/com/danum/danum/controller/board/VillageController.java
VillageController update api경로 누락으로 인해 - PutMapping("/update") 추가
=> style: Add Update API PATH Anotation

src/main/java/com/danum/danum/domain/board/question/QuestionViewDto.java, src/main/java/com/danum/danum/domain/board/village/VillageViewDto.java, src/main/java/com/danum/danum/domain/member/AuthorDto.java, src/main/java/com/danum/danum/domain/member/Member.java
마을/질문 게시판에 게시글 작성시
사용자의 정보 Email, Name, ProfileImageUrl 을 author에 담아 전달
=> refactor: Send user information to the post with author

src/main/java/com/danum/danum/domain/comment/question/QuestionComment.java, src/main/java/com/danum/danum/domain/comment/village/VillageComment.java
Qustion,VillageComment 엔티티
- 댓글 채택필드 boolean형인 isAccepted 필드에 @Builder.Default 어노테이션 사용하여 false(채택X)로 설정
=> refactor: Qustion,Village Apply isAccepted to Builder.Default annotation

src/main/java/com/danum/danum/controller/MemberController.java, src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/controller/board/VillageController.java, src/main/java/com/danum/danum/controller/comment/QuestionCommentController.java, src/main/java/com/danum/danum/controller/comment/VillageCommentController.java, src/main/java/com/danum/danum/domain/comment/question/QuestionCommentViewDto.java, src/main/java/com/danum/danum/domain/comment/village/VillageCommentViewDto.java, src/main/java/com/danum/danum/service/admin/AdminService.java, src/main/java/com/danum/danum/service/admin/AdminServiceImpl.java
기존에 있던 로직 재사용 및 구현해야할 로직 구현
관리자페이지에서 사용될 로직 및 API는 @PreAuthorize("hasRole('ADMIN')")으로 설정
=> feat: Add Administrator Logic

src/main/java/com/danum/danum/controller/GlobalExceptionHandler.java, src/main/java/com/danum/danum/controller/chat/ChatController.java, src/main/java/com/danum/danum/service/board/village/VillageServiceImpl.java, src/main/java/com/danum/danum/service/comment/QuestionCommentServiceImpl.java, src/main/java/com/danum/danum/service/comment/VillageCommentServiceImpl.java
userCheck - if (author.equals(loginUser)) -> if (!author.equals(loginUser)) 변경
=> fix: Verifying user identification

src/main/java/com/danum/danum/domain/member/UpdateDto.java, src/main/java/com/danum/danum/service/ai/OpenAiServiceImpl.java
OpenAiService 로직에서 ChatGPT 프롬프트에 사용자 위도, 경도의 위치정보를 포함하는 프롬프트 추가
Member - UpdateDto에 위도,경도 수정 필드추가
=> feat: AI 프롬프트 사용자 위치 프롬프트 추가

src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java
Question질문의 게시글에서 비회원이 볼수 있도록 view로직에서 회원을 DB에서 꺼내와 검사하는 로직삭제
=> fix: Delete user lookup logic from view logic

src/main/java/com/danum/danum/controller/comment/VillageCommentController.java, src/main/java/com/danum/danum/domain/comment/village/VillageCommentViewDto.java, src/main/java/com/danum/danum/service/comment/VillageCommentServiceImpl.java
- QuestionCommentService 로직과 동일한 구조로 리팩토링하였습니다.
- 코드 구조 및 가독성 향샹시키고, 예외처리 개선 및 관심사를 더 작고 집중된 메소드로 분리하여 재사용성에 유용하게 리팩토링하였습니다.
=> refactor: VillageCommentService 리팩토링

src/main/java/com/danum/danum/controller/board/VillageController.java, src/main/java/com/danum/danum/domain/board/village/Village.java, src/main/java/com/danum/danum/domain/board/village/VillageMapper.java, src/main/java/com/danum/danum/domain/board/village/VillageNewDto.java, src/main/java/com/danum/danum/domain/board/village/VillagePostType.java, src/main/java/com/danum/danum/domain/board/village/VillageViewDto.java, src/main/java/com/danum/danum/repository/board/VillageRepository.java, src/main/java/com/danum/danum/service/board/village/VillageService.java, src/main/java/com/danum/danum/service/board/village/VillageServiceImpl.java, src/test/java/com/danum/danum/MemberTest.java, src/test/java/com/danum/danum/QuestionCommentTest.java, src/test/java/com/danum/danum/QuestionTest.java, src/test/java/com/danum/danum/VillageCommentTest.java, src/test/java/com/danum/danum/VillageTest.java
VillagePostType enum 추가: DAILY(일상), QUESTION(질문) 유형 정의
Village 엔티티에 postType 필드 추가
VillageNewDto, VillageViewDto에 postType 필드 추가
VillageMapper에서 postType 매핑 로직 추가
VillageService와 VillageServiceImpl에 getVillagesByPostType 메소드 추가
VillageController에 게시글 유형별 조회 엔드포인트 추가
VillageRepository에 postType 기반 조회 메소드 추가
=> feat: 동네게시판 일상/질문 나누는 태그 기능

src/main/java/com/danum/danum/util/AddressParser.java
parseAddress 메소드 if-else 문을 사용하지않고, Optional의 메서드 체이닝 사용
parseValidAddress 메소드 추가
- 주소 부분들을 List로 관리
- Stream을 사용하여 빈 문자열 필터링과 문자열 결합 처리 
- 조건문 없이 선언적 방식으로 구현
=> refactor: 주소 문자열파싱로직 개선

src/main/java/com/danum/danum/service/ai/OpenAiServiceImpl.java
AI와 대화하기전 AI프롬프트에서 사용자의 위치정보를 활용하기때문에 프롬프트안에 개인정보 보호를 위해,
"단, 개인정보 보호를 위해 정확한 주소를 언급하지 말고, 지역 정보만 활용해 주세요." 라는 문구 추가
=> refactor: AI프롬프트에 사용자 개인정보 보호 입력

src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java
1. 메소드 분리 및 책임 명확화
- viewCheck 메소드를 processViewCount와 saveNewView로 분리
- likeStatus 메소드의 좋아요 처리 로직을 processLikeStatus로 분리
- 반복되는 엔티티 조회 로직을 findQuestionById, findMemberByEmail로 추출
- userCheck 메소드를 validateAuthor로 변경하여 의도를 명확히 함
2. Optional 활용 개선
- if-else 구문을 Optional의 ifPresentOrElse로 대체하여 좋아요 처리 로직 개선
- null 체크 로직을 Optional을 활용하여 안전하게 처리
3. 코드 구조화
- 핵심 비즈니스 로직을 별도 메소드로 분리
* processLikeStatus
* processViewCount
* updateQuestionContent
- 공통 유틸리티 메소드 추출
* convertToViewDto
* findQuestionById
* findMemberByEmail
4. 트랜잭션 최적화
- 읽기 전용 메소드에 @Transactional(readOnly = true) 적용 유지
- 트랜잭션 범위 명확화
[개선 이유]
1. 코드 가독성 향상
- 메소드 분리를 통해 각 기능의 의도를 명확하게 표현
- 일관된 네이밍 컨벤션 적용
2. 유지보수성 개선
- 단일 책임 원칙을 준수하여 코드 변경 시 영향도 최소화 
- 중복 코드 제거로 버그 발생 가능성 감소
3. 테스트 용이성 
- 작은 단위의 메소드로 분리하여 단위 테스트 작성 용이
- 의존성이 명확해져 테스트 케이스 작성 …
=> refactor: Question 서비스 로직 개선

src/main/java/com/danum/danum/controller/board/MainPageController.java, src/main/java/com/danum/danum/domain/board/question/QuestionViewDto.java, src/main/java/com/danum/danum/domain/board/village/VillageViewDto.java, src/main/java/com/danum/danum/repository/PostDateComparable.java, src/main/java/com/danum/danum/repository/board/QuestionRepository.java, src/main/java/com/danum/danum/repository/board/VillageRepository.java, src/main/java/com/danum/danum/service/board/question/QuestionService.java, src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java, src/main/java/com/danum/danum/service/board/village/VillageService.java, src/main/java/com/danum/danum/service/board/village/VillageServiceImpl.java
PostDateComparable 인터페이스를 추가하여 Question과 Village 게시글의 날짜 비교 기능 구현
- QuestionViewDto와 VillageViewDto에 PostDateComparable 인터페이스 적용
- created_at 필드를 기준으로 게시글 정렬 구현
검색 기능 추가
- QuestionRepository와 VillageRepository에 키워드 검색 메서드 추가
- 제목과 내용에서 키워드 검색 가능
- 검색 결과 생성일 기준 내림차순 정렬
- QuestionService와 VillageService에 검색 기능 추가
- MainPageController에 /search 엔드포인트 추가
- 통합 검색 결과 제공
- 페이징 처리 구현
최근 게시글 조회 로직 개선
- 전체 게시글 조회 후 정렬하도록 수정
- 정확한 페이징 처리를 위한 로직 개선
- 페이지 계산 방식 수정으로 페이지 이동 오류 해결
[관련 파일]
- PostDateComparable.java (신규)
- QuestionRepository.java (수정)
- VillageRepository.java (수정)
- QuestionService.java (수정)
- VillageService.java (수정)
- MainPageController.java (수정)
=> feat: 게시글 검색 기능 구현 및 최근 게시글 조회 로직 개선

src/main/java/com/danum/danum/controller/board/QuestionController.java, src/main/java/com/danum/danum/domain/board/question/Question.java, src/main/java/com/danum/danum/domain/board/question/QuestionNewDto.java, src/main/java/com/danum/danum/domain/board/question/QuestionViewDto.java, src/main/java/com/danum/danum/service/ai/OpenAiConversationServiceImpl.java, src/main/java/com/danum/danum/service/ai/OpenAiServiceImpl.java, src/main/java/com/danum/danum/service/board/question/QuestionService.java, src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java
Question 게시판에서 글을 작성시 /board/question/new를 사용하여 게시글을 생성합니다.
여기서 게시글안에 content를 사용자가 작성을 하면 자연스럽게 ai에게 질문으로 전달이되어 게시글이 생성된 동시에 ai 답변을 같이 받을수있습니다.
또한 여기서 추가적으로 ai 답변을 진행하고자하면 board/question/{questionId}/ai-chat 를통해 추가적으로 질의응답을 할수있으며 질문과 답변은 해당 게시글에 자동적으로 저장됩니다.
=> feat: Question 게시글 작성시 AI답변 기능 추가

src/main/java/com/danum/danum/controller/board/MainPageController.java
기존에 search 키워드로 검색시 페이징으로 게시글이 나오게되어있었는데 
이전에는 다음페이지로 넘어갈시 제대로 기능을 작동안한것을 수정하였습니다.
=> fix: search 페이징 기능 수정

src/main/java/com/danum/danum/controller/chat/ChatController.java, src/main/java/com/danum/danum/controller/chat/ChatRoomController.java, src/main/java/com/danum/danum/handler/ChatPreHandler.java, src/main/java/com/danum/danum/service/chat/ChatServiceImpl.java
ChatPreHandler를 통한 사용자 검증 및 인증절차 확인 로직 추가
=> refactor: 채팅 로직 수정

src/main/java/com/danum/danum/service/board/question/QuestionServiceImpl.java
show/Id 를 해서 하면 채택여부를 알수있지만
show를 하여서 보면 페이징기능에 일부 기능이 누락되었던것을 추가하였습니다.
=> feat: ViewList에 채택필드 추가
